export const UPDATE_NAME = 'UPDATE_NAME';
export const UPDATE_SUBCATEGORY = 'UPDATE_SUBCATEGORY';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION';
export const UPDATE_DURATION = 'UPDATE_DURATION';
export const UPDATE_PRICE = 'UPDATE_PRICE';
