export const GET_COMPANY_SERVICES = 'GET_COMPANY_SERVICES';
export const DELETE_COMPANY_SERVICE = 'DELETE_COMPANY_SERVICE';
export const GET_COMPANY_IMAGES = 'GET_COMPANY_IMAGES';
export const DELETE_COMPANY_IMAGE = 'DELETE_COMPANY_IMAGE';
export const RESET = 'RESET';
