export const UPDATE_CLIENT_NAME = 'UPDATE_CLIENT_NAME';
export const UPDATE_CLIENT_PHONE = 'UPDATE_CLIENT_PHONE';
export const UPDATE_CLIENT_COMMENT = 'UPDATE_CLIENT_COMMENT';
export const UPDATE_ORDER_DATE = 'UPDATE_ORDER_DATE';

export const GET_ORDERS = 'GET_ORDERS';
export const CREATE_ORDER = 'CREATE_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
