export const UPDATE_WEEK = 'UPDATE_WEEK';
export const UPDATE_START_TIME = 'UPDATE_START_TIME';
export const UPDATE_FINISH_TIME = 'UPDATE_FINISH_TIME';
export const ADD_DAY = 'ADD_DAY';
export const UPDATE_SELECTED_DAY = 'UPDATE_SELECTED_DAY';
export const ACTIVE_DAY = 'ACTIVE_DAY';
