export const NEXT = 'NEXT';
export const BACK = 'BACK';
export const UPDATE_SERVICE_NAME = 'UPDATE_SERVICE_NAME';
export const UPDATE_SERVICE_ADDRESS = 'UPDATE_SERVICE_ADDRESS';
export const UPDATE_START_TIME = 'UPDATE_START_TIME';
export const UPDATE_FINISH_TIME = 'UPDATE_FINISH_TIME';
